<?php

namespace Container2SodwBb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TOz6_QCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tOz6.qC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tOz6.qC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carsRepository' => ['privates', 'App\\Repository\\CarsRepository', 'getCarsRepositoryService', true],
        ], [
            'carsRepository' => 'App\\Repository\\CarsRepository',
        ]);
    }
}
