<?php

namespace Container2SodwBb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LDa1AvTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LDa1AvT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LDa1AvT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cars' => ['privates', '.errored..service_locator.LDa1AvT.App\\Entity\\Cars', NULL, 'Cannot autowire service ".service_locator.LDa1AvT": it references class "App\\Entity\\Cars" but no such service exists.'],
        ], [
            'cars' => 'App\\Entity\\Cars',
        ]);
    }
}
