<?php

namespace ContainerXCs3HUx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LDa1AvT.App\Entity\Cars' shared service.
     *
     * @return \App\Entity\Cars
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LDa1AvT": it references class "App\\Entity\\Cars" but no such service exists.');
    }
}
