vich_uploader:
    metadata:
        type: attribute
    db_driver: orm

    mappings:
        cars:
            uri_prefix: '%cars_attachments%'
            upload_destination: '%kernel.project_dir%/public%cars_attachments%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
