<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXCs3HUx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXCs3HUx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXCs3HUx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXCs3HUx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXCs3HUx\App_KernelDevDebugContainer([
    'container.build_hash' => 'XCs3HUx',
    'container.build_id' => '71a64793',
    'container.build_time' => 1677163522,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXCs3HUx');
